---
title: "FDAPDE Areal"
format: pdf
editor: visual
---

```{r}
library(tidyverse)
library(fdaPDE)
library(dplyr)
library(terra)
library(raster)
library(rnaturalearth)
library(INLA)
library(sf)
library(ggplot2)
library(mapview)
library(viridis)
```

```{r}
data_sf = st_read("Counties/shapefiles/lungcancer.shp")
map <- ne_countries(type = "countries",
                    country = "Ireland",
                    scale = "large", returnclass = "sf")

# 1. Assign EPSG:2157 if not already set
st_crs(data_sf) <- 2157
```

```{r}
yr = 2022
data_year = data_sf |> filter(Year == yr)

# 2. Transform to WGS84 (lat/lon)
data_year_transformed <- st_transform(data_year, crs = 4326)

# 3. Extract the lat/lon from geometry
centroids <- st_centroid(data_year_transformed)
```

```{r}
mapview(centroids, zcol = "value")
```

```{r}
latlon = st_coordinates(centroids)
data_filtered = data.frame(value = centroids$value, Longitude = latlon[,"X"], Latitude = latlon[,"Y"])
data_filtered

data_sf = st_as_sf(data_filtered, coords = c("Longitude","Latitude"), crs=sf::st_crs(map))
  
#filter out data points which lie outside the map boundaries
data_sf = st_filter(data_sf, map)

#z = scale(data_filtered$value)

#make grid for mesh
sq100 <- sf::st_make_grid(map, n = c(50,25)) # rect grid on bbox
tri_pts <- sf::st_coordinates(sf::st_centroid(sq100[sf::st_union(map)])) # Triangulation points
outer_pts <- sf::st_coordinates(sf::st_union(sq100[sf::st_union(map)])) # boundary points
plot(outer_pts)

tri_pts = rbind(outer_pts[, 1:2], tri_pts) # combine boundary points and inner points
tri_pts = tri_pts[!duplicated(tri_pts),]
tri_seg <- cbind(1:(nrow(outer_pts)-1), c(2:(nrow(outer_pts)-1),1))
tri_mesh  = create.mesh.2D(nodes = tri_pts, segments = tri_seg)
tri_meshr = refine.mesh.2D(tri_mesh,minimum_angle = 30,maximum_area = 0.03)
plot(tri_meshr)
points(data_sf, col = "red")
FEM_basis <- fdaPDE::create.FEM.basis(tri_mesh)
FEM_fit <- fdaPDE::smooth.FEM(as.matrix(data_filtered[,c(2,3)]), data_filtered[,1], FEM_basis, lambda = 10^seq(-6,6),
                              DOF.evaluation = 'exact', 
                              lambda.selection.lossfunction = 'GCV')
```

```{r}
preds = data_filtered |> dplyr::select(Longitude, Latitude) |> as.matrix()
predictions = fdaPDE::eval.FEM(FEM_fit$fit.FEM, preds)

data_year$preds = predictions
data_year$preds = as.vector(data_year$preds)

st_write(data_year, "areal_outputs/fdapde/lungcancer_predictions.shp", delete_layer = TRUE)

mapview(data_year, zcol = "preds")
```

```{r}
grid <- terra::rast(map, nrows = 200, ncols = 200)
xy <- terra::xyFromCell(grid, 1:ncell(grid))
dp <- st_as_sf(as.data.frame(xy), coords = c("x", "y"),
               crs = st_crs(map))
indicespointswithin <- which(st_intersects(dp, map,
                                           sparse = FALSE))
dp <- st_filter(dp, map)
pred_coords = st_coordinates(dp) #predict for these points. around 20000 data points which lie inside the map.

FEM_zfit <- fdaPDE::eval.FEM(FEM_fit$fit.FEM, pred_coords)

#mean_z <- attr(z, "scaled:center")
#sd_z <- attr(z, "scaled:scale")

#pred_values <- FEM_zfit * sd_z + mean_z

output = cbind(pred_coords, FEM_zfit)
#output[,3] = sqrt(output[,3])

#make rastor object for plotting
r <- terra::rast(output, type = "xyz")
crs(r) <- "EPSG:4326"

mapview(r)
```
