---
title: "Process Lung cancer dataset"
format: pdf
editor: visual
---

```{r}
library(sf)
library(tidyverse)
library(ggplot2)
library(mapview)
```

```{r}
lung_cancer <- read_delim("Cancer Data/Cancers.csv", delim = "\t", locale = locale(encoding = "UTF-16LE"))
lung_cancer = lung_cancer |> filter(Sex == "Both") |> dplyr::select(Region, Year, `Case Numbers`)
lung_cancer$Region = toupper(lung_cancer$Region)
lung_cancer = lung_cancer |> filter(! (Region %in% c("DUBLIN NORTH", "DUBLIN SOUTH", "HSE DUBIN SOUTH EAST", "HSE DUBLIN MID LEINSTER", "HSE DUBLIN NORTH EAST", "HSE SOUTH WEST", "HSE WEST", "HSE WEST NORTH WEST", "IRELAND", "TIPPERARY NORTH", "TIPPERARY SOUTH")))
lung_cancer$Region[lung_cancer$Region == "DUBLIN (TOTAL)"] = "DUBLIN"
lung_cancer$Region[lung_cancer$Region == "TIPPERARY (TOTAL)"] = "TIPPERARY"
lung_cancer$`Case Numbers` = as.numeric(lung_cancer$`Case Numbers`)
lung_cancer$value = log1p(lung_cancer$`Case Numbers`)
```

```{r}
map = st_read("Counties/Counties___OSi_National_Statutory_Boundaries_7992851692716515542.gpkg")
map = map |> dplyr::select(ENGLISH, SHAPE) |> rename(Region = ENGLISH)
```

```{r}
lung_cancer_sf = lung_cancer |> left_join(map, by = "Region") |> st_as_sf()
st_write(lung_cancer_sf, "Counties/shapefiles/lungcancer.shp")
plt = lung_cancer_sf |> filter(Year == 2022)
mapview(plt, zcol = "value") 
```
